### ISSUE TITLE
AI does not get combat notifications

### ISSUE THREAD

**Issue by Teebeutel** [FTL13/FTL13#201] opened 2016-10-16 14:18 UTC
**Problem Description**:
During combat the AI does not get notified of ships jumping around the system as well as incoming or outgoing fire.

**What did you expect to happen**: 
It would stand to reason that if the crew gets notified of these events, the AI should be, as well.

**What happened instead**:
The AI does not get notified

**Why is this bad/What are the consequences:**
It makes combat a bit chaotic as the AI and it is hard to help the crew at times.

**Steps to reproduce the problem**:
Play the AI, intiate combat.

**Comment by monster860** [comment] 2016-10-16 14:22
Duplicate of #103

**Closed by monster860** 2016-10-16 14:22 UTC
