### ISSUE TITLE
[Suggestion] FoB check if in transit

### ISSUE THREAD

**Issue by HawkerTheGreat** [FTL13/FTL13#3558] opened 2018-05-27 17:48 UTC
Just want to put this here, in case anyone gets sick and tired of their miners committing suicide in FTL or not communicating with you, then blaming it on you as your lovely FoB comes back as a slab of floor tiles and they re-clone.

If we have all this space age technology can we at least have the Ship/FoB check if the other one is in transit/spool up and deny them from moving if this is the case?... It would prevent so many deaths and no longer would we have to worry about the fact nobody actually understands mining.

If you have something to add or suggestions, please comment - tell me where I'm wrong, I understand that this could have repercussions if abused.

**Comment by HawkerTheGreat** [comment] 2018-05-27 18:09
https://github.com/FTL13/FTL13/issues/3508

Totally didnt see that, but heres another issue of the same kind.

**Comment by TMTIME** [comment] 2018-05-27 18:19
FOB should be throwing out an error message + preventing it from moving if the main ship is either in transit or spooling up

Also the shuttles should be keeping the area they are in loaded now

**Comment by Vivalas** [comment] 2018-06-05 04:18
Ahhh

**Comment by Vivalas** [comment] 2018-06-05 04:19
Wait no duplicate of #3508

**Closed by Vivalas** 2018-06-05 04:20 UTC
Labels: Feature Request
