### ISSUE TITLE
Virology patient room not accessible by virologist

### ISSUE THREAD

**Issue by Chickenmonster1** [FTL13/FTL13#110] opened 2016-08-12 21:36 UTC
**Problem Description**:
What is the problem?
The door to the small room in virology doesn't have proper access levels.
**What did you expect to happen**: 
Why do you think this is a bug?
Not a bug, just wrong access levels
**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment] 2016-08-12 21:38
Duplicate of #104

**Closed by monster860** 2016-08-12 21:38 UTC
Labels: Duplicate, Map Issue
