### ISSUE TITLE
Cyborg power cells too small.

### ISSUE THREAD

**Issue by Superhats** [FTL13/FTL13#211] opened 2016-10-23 19:52 UTC
**Problem Description**:
What is the problem?
The cyborg's power cells are too small
**What did you expect to happen**: 
Why do you think this is a bug?
It isn't a bug but an issue, as current cells get consumed in 3 minutes
**What happened instead**:
How is what happened different from what you expected?
A basic power cell usually lasts at least 30 minutes.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It really limits what you can do as a cyborg. [RCD can't be used]
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Gouty** [comment] 2016-10-23 23:15
Duplicate of #210

**Comment by yashaldie** [comment] 2016-10-29 01:52
should be good to close this one now.

**Closed** 2016-10-29 12:46 UTC
Labels: Inconsistency
