### ISSUE TITLE
 Undocking from Planets Impossible/ FTL Drive Broken After Jumping

### ISSUE THREAD

**Issue by Siderivers** [FTL13/FTL13#851] opened 2017-06-05 21:23 UTC
- It is impossible to undock from a planet; only way to leave is jumping out.

- FTL drive and shield generator will disappear after making either a FTL jump or interplanetary jump. At this point, it is still possible to make either jump as the FTL drive will still be charging without the FTL drive but when the jump is completed, every thing will be deleted out of the ship leaving nothing but the walls and floors. The following will happen depending on what type of jump is done:

After making a FTL jump to another sector, everything will despawn and the ship will become empty with nothing but the walls and floors. Depending on what planet the ship ends up orbiting in when that jump is completed, the following will happen (assuming that what happening after the FTL jump is the same thing happening after an interplanetary jump to a planet is completed. The below events are based on what happens after making an interplanetary jump):

When jumping into a lava, habitable, or ice planet without a station, the ship will be deleted and the z-level will be loaded with the planet's surface on top of it.

When jumping into a gas giant with or without a station, the ship's outline will remain. Depending if there was a station or not, the station's items will load.

When jumping into an ice planet, habitable exoplanet, or lava planet with a station within a system, the planet’s surface will not load but space ruins will still load if any and the orbiting station will load with items. The ship, however, will be deleted.

Disclaimer: I am assuming that it does not matter if the planet was ringed or not.

**Comment by Vivalas** [comment] 2017-06-10 01:27
:fire:

**Comment by ike709** [comment] 2017-06-10 01:33
Confirmed. Also I made a dupe of this because I forgot there was a github issue for it

**Comment by ike709** [comment] 2017-06-12 03:38
This is fixed @ninjanomnom

**Closed** 2017-06-12 03:39 UTC
Labels: FUCK
