### ISSUE TITLE
Chef Table Stun

### ISSUE THREAD

**Issue by Desolane** [FTL13/FTL13#300] opened 2016-12-10 23:52 UTC
**Problem Description**:
If you climb on the chef's table to try and break into the kitchen, you will be frozen on top of it for what feels like 5 minutes. Literally.

**What did you expect to happen**: 
A normal stun of like, 5 seconds.

**What happened instead**:
The stun time is unbelievably long.

**Why is this bad/What are the consequences:**
People shouldn't freeze for 5 minutes when climbing on a table.

**Steps to reproduce the problem**:
Climb on the table to try and break into the kitchen. Then try to move or look anywhere.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No the lag was ordinary.

**Comment by Vivalas** [comment] 2016-12-12 05:06
I'm going to try to reproduce this but it may have been caused by a mixture of the warp knockdown and / or the MC shutting off. Do you have any details of the situation? Unless I can reproduce this this bug is too vague to be valid, especially since the tables used in the kitchen counter are the same as all the others on the ship and shouldn't stun any differently.

**Comment by Vivalas** [comment] 2017-04-07 00:58
Probably because of MC lag, closing.

**Closed by Vivalas** 2017-04-07 00:58 UTC
Labels: Working As Intended™
