### ISSUE TITLE
Phase cannon faces one way but shoots the other

### ISSUE THREAD

**Issue by Vivalas** [FTL13/FTL13#33] opened 2016-07-29 01:09 UTC
This is a weird one I noticed today. After you guys upgraded it, the sprite was facing east but the bolts were being shot south. I don't know how to reproduce it or what causes it, just that I believe it was related to being upgraded.

**Comment by Vivalas** [comment] 2016-07-29 22:13
This will be important after I rework weapons since the bolts won't be leaving the map and thus won't be registering as hits

**Comment by CrAzYPiLoT-SS13** [comment] 2016-07-31 09:47
I couldn't reproduce. You sure someone didn't rotate it?

**Comment by Vivalas** [comment] 2016-08-01 05:23
I'm almost certain it was facing east yet shooting south. I'm fine with you closing this until it comes back up (???). I don't even know how this would be possible.

**Comment by CrAzYPiLoT-SS13** [comment] 2016-08-31 18:49
I literally tried every possible way of reproducing this, no dice. Feel free to reopen it if it happens again.

**Comment by Vivalas** [comment] 2016-09-26 22:59
Just saying this happened again in a recent test round.

**Comment by monster860** [comment] 2016-12-05 14:45
I think this bug is fixed with the new cannon sprites.

**Closed by monster860** 2016-12-05 14:45 UTC
Labels: Bug, WTF
