### ISSUE TITLE
power cell in borgs 

### ISSUE THREAD

**Issue by chaosyourgod** [FTL13/FTL13#318] opened 2016-12-18 01:57 UTC
it seems like no matter what kinda cell you put into a borg it'll always have the shitty cells cap of 1750

**Comment by chaosyourgod** [comment] 2016-12-18 02:44
actually I've found that ALL of the power cells have a shit cap to them which suggest they've all been lowered vasty

**Comment by MrJJJ2** [comment] 2016-12-18 09:02
I belive this is intentional, since if you could put 5000-10000+ cell cap into phase cannons, they would become OP as hell and you could take down entire armada of 50+ ships before even half get to fire.

**Comment by Vivalas** [comment] 2017-04-07 00:59
duplicate of #312

**Closed by Vivalas** 2017-04-07 00:59 UTC
Labels: Oversight
