### ISSUE TITLE
HoP job changes do not update slots filled

### ISSUE THREAD

**Issue by TopFug** [FTL13/FTL13#299] opened 2016-12-10 20:46 UTC
**Problem Description**:
While as HoP, changing someone's position will not update the slot being filled/unfilled, i.e. changing a Scientist's to Research Director will not open a Scientist slot and the RD slot still appears open

**What did you expect to happen**: 
Under normal circumstances changing positions would unfill and fill the changes made from the console

**What happened instead**:
Redundant, but you end up with several heads of the same bay or several single slot positions being filled

**Why is this bad/What are the consequences:**
An example of an issue is that once I had changed a Scientist into the Research Director, within 2 minutes someone signed up as Research Director. This lead to two RD's.

**Steps to reproduce the problem**:
Reassign someone's position to another, it can be any position, the best to test would be for head roles

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
On an unrelated note, the HoP console has no EVA access to give as well as there being no PTech machine to vend PDAs or cartridges.

**Comment by Qustinnus** [comment] 2016-12-10 22:49
You can manually change the slots to open or closed as well, you know.

**Comment by TopFug** [comment] 2016-12-10 23:15
Not for department head positions, and it doesn't actually work for the fact that a scientist who has had his job changed will still leave a scientist slot filled

**Comment by Qustinnus** [comment] 2016-12-10 23:16
Fair, I do know that the HoP console has always been very buggy in FTL13 so I hope this gets fixed then.

**Comment by Vivalas** [comment] 2017-04-07 00:58
I'm pretty sure this is the behavior on all servers and is not a bug, so I'm gonna label it a feature request for now.

**Closed** 2017-04-09 21:24 UTC
Labels: Feature Request
