### ISSUE TITLE
Supermatter broken on FTL map?

### ISSUE THREAD

**Issue by Nightcaper** [FTL13/FTL13#138] opened 2016-08-17 18:00 UTC
**Problem Description**:
When the Supermatter engine is set up according to the FTL13 wiki entry (http://ftl13.com/wiki/index.php?title=Supermatter_Engine), the core almost always laminates, with no emergency procedure able to stop it.

**What did you expect to happen**: 
The Supermatter should have been supplying power without issue from setting it up according to the wiki entry. At the very least the emergency procedures should have worked.

**What happened instead**:
The SMES waned from charging and not charging, seeming to not get enough power. Within minutes of setting the core up, it started becoming instable. All emergency procedures for lamination were taken as early as possible, with no end in sight.

**Why is this bad/What are the consequences:**
Station power is essential to actually playing the map. If it's broken from the get-go, new players who haven't set up Supermatter engines before (me) won't know what they've done wrong!

**Steps to reproduce the problem**:
Set up the Supermatter Engine according to the following instructions: http://ftl13.com/wiki/index.php?title=Supermatter_Engine

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I was using the FTL specific map in this case. I followed the wiki instructions to the letter, because I have never set up the Supermatter before. I have no idea how pressures, temperatures and such should be done, because it's my first time and I don't know what to expect. The SMES didn't seem to be charging much, I noticed that. All emergency procedures to cease core lamination did not work, and I had to eject. This happened to my two friends who ALSO tried a round setting it up. It can't just be my incompetence at following instructions.

If this is error on my part, please teach me how to properly set it up or even modify the wiki entry. Remember that this is my first time even setting up the engine, and we're among a group of friends where I'm one of the best engineers (god help us).

**Comment by CrAzYPiLoT-SS13** [comment] 2016-09-29 14:28
Couldn't reproduce. People have successfully set up the engine in our test rounds. I cannot really help you, other than tell you to re-read the wiki article and ask around on the Discord or forum. Closing this.

**Closed by CrAzYPiLoT-SS13** 2016-09-29 14:28 UTC
Labels: Map Issue
