### ISSUE TITLE
Players can get themselves into empty planetgen zlevel

### ISSUE THREAD

**Issue by ghost** [FTL13/FTL13#586] opened 2017-03-26 14:57 UTC
**Problem Description**:
See title. I doubt this zone should be accessible.

**What did you expect to happen**: 
Player bash his head at invisible world border. His head hurts a little. Universe decided he's not ready to know it's secrets yet.

**What happened instead**:
Universe went full retard:
![image](https://cloud.githubusercontent.com/assets/26148443/24331979/e1605dfe-1257-11e7-9035-91687e1ff2c8.png)
after ship jumped poor guy found himself here:
![image](https://cloud.githubusercontent.com/assets/26148443/24331994/1c361fc2-1258-11e7-9224-acb2ff841610.png)
and now some weird power teleports him into room with undestructible walls and fakedoor.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
Nervere - Today at 19:07
We were going salvaging after killing four syndicate drones. We found an asteroid even though this planet isn't ringed. I was able to make it back to the ship just fine even though I was just with the player who made it to planetgen. (I'm the captain, he was the guy in CE gear flying around.

Nervere - Today at 19:07
We found no salvage.
I think he went south of the asteroid by accident and ended up on a different non-restricted z-level.

**Comment by ninjanomnom** [comment] 2017-06-16 07:52
duplicate of #374

**Closed by ninjanomnom** 2017-06-16 07:52 UTC
Labels: A Monster860 Planet / Power Fuckup, Bug, FUCK
